### PR TITLE
Update JAB to 17.0.9

### PR DESCRIPTION
**Pull request by seanbudd**
Updated the dll file following the README steps.

Smoke tested with PyCharm.

If there are known smoke testing steps, these should be added to the README.

### CODE REVIEW

**Comment by seanbudd** [comment]
@mwhapples - would you be able to smoke test our update to JAB or suggest smoke testing steps?

Here is a build to test with:
https://ci.appveyor.com/api/buildjobs/9jkp295qfgi9mkuj/artifacts/output%2Fnvda_snapshot_try-JAB-17-29837%2Cfd1942a2.exe

**Comment by mwhapples** [comment]
I will give it testing today.

**Comment by mwhapples** [comment]
As an aside, are you aware that (java 21 is out and that is supposed to be LTS, so would it be better to go to (java 21 JAB?

**Comment by seanbudd** [comment]
Zulu isn't offering a 32bit build of 21 unfortunately, I'm not sure if 32bit support is fully dropped in that release or they just haven't made a build yet

**Comment by seanbudd** [comment]
I see 32bit was deprecated in 21, probably why they didn't create a build

https://openjdk.org/jeps/449

**Comment by mwhapples** [comment]
As my projects using Java are only targetted for 64-bit systems, I didn't notice that X86 32-bit was deprecated in 21. I have looked around and seems like all the OpenJDK builds no longer include 32-bit (eg. adoptium, Azul, Microsoft, Amazon corretto, etc).

**Comment by mwhapples** [comment]
Yesterday I tried the build and did not notice anything untoward, at least not compared with existing JAB support. However I was using it whilst working in PyCharm, so its more real world testing than methodical testing of different Java components.

**Comment by seanbudd** [comment]
Thanks for the testing, it is appreciated

**Comment by akash07k** [comment]
@seanbudd  Will it improve anything for the accessibility of existing java applications such as Android Studio?

**Comment by mwhapples** [comment]
There are some Java Access bugs I am fairly sure which will not be affected by this change, unfortunately they would require API changes to the Java Access Bridge or for NVDA to do something more intelligent with what it gets. One such example would be notification/announcing expanding/collapsing treeview items. This is not to say there won't be any improvements, but I doubt they are going to be anything major.

**Comment by mwhapples** [comment]
I will still give it some testing whilst using (java based applications.

**Pull request merged**
